# Generated by Django 2.1.8 on 2019-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dresstk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateField(blank=True, db_column='日期_Date', max_length=255, null=True)),
                ('d1', models.FloatField(blank=True, db_column='开盘价_Oppr', max_length=255, null=True)),
                ('d2', models.FloatField(blank=True, db_column='最高价_Hipr', max_length=255, null=True)),
                ('d3', models.FloatField(blank=True, db_column='最低价_Lopr', max_length=255, null=True)),
                ('d4', models.FloatField(blank=True, db_column='收盘价_Clpr', max_length=255, null=True)),
                ('d5', models.CharField(blank=True, db_column='成交量_Trdvol', max_length=255, null=True)),
                ('d6', models.CharField(blank=True, db_column='最新股票名称_Lstknm', max_length=255, null=True)),
            ],
            options={
                'db_table': '股票',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
