# Generated by Django 2.1.8 on 2019-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showproject', '0002_auto_20190724_2104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dresstk',
            table='广誉远',
        ),
    ]
