# Generated by Django 2.1.8 on 2019-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showproject', '0004_dataoffline_dataonline_dataproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(blank=True, max_length=255, null=True)),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'off_range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnRange',
            fields=[
                ('chars', models.CharField(blank=True, max_length=255, null=True)),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'on_range',
                'managed': False,
            },
        ),
    ]
